services:
  front:
    build:
      context: ./front
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/app  # ← ローカルの ./front をコンテナの /app にマウント
      - /app/node_modules  # ← node_modules はコンテナ内のものを使う（重要）
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: .devcontainer/Dockerfile
    # overrideされないっぽいので一旦コメントアウト
    # ports:
    #   - "8080:8080"
    #   - "40000:40000"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - NGINX_BACKEND_URL=${NGINX_BACKEND_URL}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  mongo:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db

  proxy:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - ./.ssl:/etc/ssl/certs
    depends_on:
      - front
      - backend
    
volumes:
  mongo-data:
