version: '3.9'

services:
  front:
    build:
      context: ./front
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./front:/app

  backend:
    build:
      context: ./backend
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  mongo:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
