package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
)

// CheckAdmin is the resolver for the checkAdmin field.
func (r *queryResolver) CheckAdmin(ctx context.Context) (bool, error) {
	// ディレクティブで認証が完了している
	return true, nil
}
