package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/graphModel"
	"context"
	"fmt"
)

// Data is the resolver for the data field.
func (r *queryResolver) Data(ctx context.Context, name string) (*graphModel.AffiliateData, error) {
	panic(fmt.Errorf("not implemented: Data - data"))
}
