package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/api/category"
	"backend/graph/model"
	"context"
)

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	catList, err := category.GetCategoryList()
	if err != nil {
		return nil, err
	}
	modelCatList := make([]*model.Category, len(catList))
	for i, cat := range catList {
		modelCatList[i] = category.ConvertToModelCategory(cat)
	}
	return modelCatList, nil
}
