package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/graphModel"
	"context"
	"fmt"
)

// RegisterTag is the resolver for the registerTag field.
func (r *mutationResolver) RegisterTag(ctx context.Context, tag string) (*graphModel.User, error) {
	panic(fmt.Errorf("not implemented: RegisterTag - registerTag"))
}

// GetTagsForLiquor is the resolver for the getTagsForLiquor field.
func (r *queryResolver) GetTagsForLiquor(ctx context.Context, id string) ([]*graphModel.Tag, error) {
	panic(fmt.Errorf("not implemented: GetTagsForLiquor - getTagsForLiquor"))
}
