package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend/graph/graphModel"
	"context"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// GetUserByID is the resolver for the getUserById field.
func (r *queryResolver) GetUserByID(ctx context.Context, id string) (*graphModel.User, error) {
	uObjID, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	user, err := r.UserRepo.GetById(ctx, uObjID)
	if err != nil {
		return nil, err
	}
	return user.ToGraphQL(), nil
}
