// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID       int         `json:"id"`
	Name     string      `json:"name"`
	Parent   *int        `json:"parent,omitempty"`
	Children []*Category `json:"children,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
