// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphModel

import (
	"time"
)

type Category struct {
	ID       int         `json:"id"`
	Name     string      `json:"name"`
	Parent   *int        `json:"parent,omitempty"`
	Children []*Category `json:"children,omitempty"`
}

type Liquor struct {
	ID           string    `json:"id"`
	CategoryID   int       `json:"categoryId"`
	CategoryName string    `json:"categoryName"`
	Name         string    `json:"name"`
	Description  *string   `json:"description,omitempty"`
	ImageURL     *string   `json:"imageUrl,omitempty"`
	ImageBase64  *string   `json:"imageBase64,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Query struct {
}
