// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"backend/api"
	"backend/api/post/categoryPost"
	"backend/api/post/liquorPost"
	"backend/db"
	"backend/db/repository/bookmarkRepository"
	"backend/db/repository/categoriesRepository"
	"backend/db/repository/errorRepository"
	"backend/db/repository/flavorMapRepository"
	"backend/db/repository/liquorRepository"
	"backend/db/repository/userRepository"
	"backend/di/handlers"
	"backend/graph"
	"backend/graph/resolver"
	"backend/router"
	"backend/service/authService/tokenConfig"
	"backend/util/amazon/s3"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeHandler() (*gin.Engine, error) {
	client, err := db.NewMongoClient()
	if err != nil {
		return nil, err
	}
	dbDB := db.NewDB(client)
	database := db.ProvideMongoDatabase(dbDB)
	categoryRepository := categoriesRepository.NewCategoryRepository(dbDB)
	liquorsRepository := liquorRepository.NewLiquorsRepository(dbDB)
	usersRepository := userRepository.NewUsersRepository(dbDB)
	bookMarkRepository := bookmarkRepository.NewBookMarkRepository(dbDB)
	flavorMapRepositoryFlavorMapRepository := flavorMapRepository.NewFlavorMapRepository(dbDB)
	flavorMapMasterRepository := flavorMapRepository.NewFlavorMapMasterRepository(dbDB)
	flavorToLiquorRepository := flavorMapRepository.NewFlavorToLiquorRepository(dbDB)
	tokenConfigTokenConfig := tokenConfig.NewTokenConfig()
	resolverResolver := resolver.NewResolver(database, categoryRepository, liquorsRepository, usersRepository, bookMarkRepository, flavorMapRepositoryFlavorMapRepository, flavorMapMasterRepository, flavorToLiquorRepository, tokenConfigTokenConfig)
	server := graph.NewGraphQLServer(resolverResolver)
	s3S3, err := s3.NewS3Client()
	if err != nil {
		return nil, err
	}
	handler := liquorPost.NewHandler(database, s3S3, categoryRepository, liquorsRepository, usersRepository)
	categoryPostHandler := categoryPost.NewHandler(database, s3S3, categoryRepository)
	userHandler := api.NewUserHandler(database, usersRepository)
	errorsRepository := errorRepository.New(dbDB)
	handlersHandlers := handlers.NewHandlers(handler, categoryPostHandler, tokenConfigTokenConfig, userHandler, errorsRepository)
	engine := router.Router(server, handlersHandlers)
	return engine, nil
}
